collections:
- name: fedora.linux_system_roles
  version: 1.35.0
- name: ansible.netcommon
  version: 4.1.0
- name: ansible.posix
  version: 1.5.1
- name: community.crypto
  version: 2.10.0
- name: community.general
  version: 6.3.0
