collections:
- name: fedora.linux_system_roles
  version: 1.30.5
- name: ansible.netcommon
  version: 4.1.0
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.9.0
- name: community.general
  version: 6.0.1
