collections:
- name: ansible.netcommon
  version: 8.0.0
- name: ansible.posix
  version: 2.0.0
- name: ansible.utils
  version: 6.0.0
- name: community.crypto
  version: 2.26.3
- name: community.general
  version: 10.7.0
- name: fedora.linux_system_roles
  version: 1.101.1
