collections:
- name: fedora.linux_system_roles
  version: 1.8.1
- name: ansible.netcommon
  version: 2.3.0
- name: ansible.posix
  version: 1.2.0
- name: community.crypto
  version: 1.7.1
- name: community.general
  version: 3.4.0
