collections:
- name: ansible.netcommon
  version: 6.0.0
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 4.0.0
- name: community.crypto
  version: 2.18.0
- name: community.general
  version: 8.5.0
- name: fedora.linux_system_roles
  version: 1.75.3
