collections:
- name: fedora.linux_system_roles
  version: 1.17.0
- name: ansible.netcommon
  version: 2.6.0
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.2.2
- name: community.general
  version: 4.5.0
