collections:
- name: fedora.linux_system_roles
  version: 1.26.0
- name: ansible.netcommon
  version: 3.1.0
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.4.0
- name: community.general
  version: 5.4.0
