collections:
- name: ansible.netcommon
  version: 7.0.0
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 5.0.0
- name: community.crypto
  version: 2.20.0
- name: community.general
  version: 9.1.0
- name: fedora.linux_system_roles
  version: 1.79.0
