collections:
- name: fedora.linux_system_roles
  version: 1.35.2
- name: ansible.netcommon
  version: 5.0.0
- name: ansible.posix
  version: 1.5.1
- name: community.crypto
  version: 2.11.1
- name: community.general
  version: 6.5.0
