collections:
- name: fedora.linux_system_roles
  version: 1.18.0
- name: ansible.netcommon
  version: 2.6.1
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.2.3
- name: community.general
  version: 4.6.0
