collections:
- name: ansible.netcommon
  version: 8.2.0
- name: ansible.posix
  version: 2.1.0
- name: ansible.utils
  version: 6.0.0
- name: community.crypto
  version: 3.0.5
- name: community.general
  version: 12.0.1
- name: fedora.linux_system_roles
  version: 1.111.0
