collections:
- name: ansible.netcommon
  version: 7.1.0
- name: ansible.posix
  version: 1.6.1
- name: ansible.utils
  version: 5.1.2
- name: community.crypto
  version: 2.22.2
- name: community.general
  version: 9.5.0
- name: fedora.linux_system_roles
  version: 1.88.9
