collections:
- name: fedora.linux_system_roles
  version: 1.15.2
- name: ansible.netcommon
  version: 2.5.1
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.2.1
- name: community.general
  version: 4.4.0
