collections:
- name: fedora.linux_system_roles
  version: 1.41.1
- name: ansible.netcommon
  version: 5.1.1
- name: ansible.posix
  version: 1.5.4
- name: community.crypto
  version: 2.14.0
- name: community.general
  version: 7.0.1
