collections:
- name: fedora.linux_system_roles
  version: 1.38.1
- name: ansible.netcommon
  version: 5.1.0
- name: ansible.posix
  version: 1.5.2
- name: community.crypto
  version: 2.13.0
- name: community.general
  version: 6.6.0
