collections:
- name: fedora.linux_system_roles
  version: 1.53.0
- name: ansible.netcommon
  version: 5.1.2
- name: ansible.posix
  version: 1.5.4
- name: community.crypto
  version: 2.15.0
- name: community.general
  version: 7.3.0
