collections:
- name: fedora.linux_system_roles
  version: 1.14.0
- name: ansible.netcommon
  version: 2.5.0
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.1.0
- name: community.general
  version: 4.3.0
