collections:
- name: fedora.linux_system_roles
  version: 1.53.5
- name: ansible.netcommon
  version: 5.2.0
- name: ansible.posix
  version: 1.5.4
- name: community.crypto
  version: 2.15.1
- name: community.general
  version: 7.4.0
