collections:
- name: fedora.linux_system_roles
  version: 1.26.1
- name: ansible.netcommon
  version: 3.1.1
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.5.0
- name: community.general
  version: 5.6.0
