collections:
- name: fedora.linux_system_roles
  version: 1.52.2
- name: ansible.netcommon
  version: 5.1.2
- name: ansible.posix
  version: 1.5.4
- name: community.crypto
  version: 2.14.1
- name: community.general
  version: 7.2.1
