collections:
- name: ansible.netcommon
  version: 6.1.1
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 4.1.0
- name: community.crypto
  version: 2.19.0
- name: community.general
  version: 8.6.0
- name: fedora.linux_system_roles
  version: 1.76.2
