collections:
- name: fedora.linux_system_roles
  version: 1.10.0
- name: ansible.netcommon
  version: 2.4.0
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 1.9.5
- name: community.general
  version: 3.8.0
