collections:
- name: fedora.linux_system_roles
  version: 1.27.0
- name: ansible.netcommon
  version: 4.0.0
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.7.1
- name: community.general
  version: 5.7.0
