collections:
- name: fedora.linux_system_roles
  version: 1.23.0
- name: ansible.netcommon
  version: 3.0.1
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.3.1
- name: community.general
  version: 5.0.1
