collections:
- name: ansible.netcommon
  version: 7.2.0
- name: ansible.posix
  version: 2.0.0
- name: ansible.utils
  version: 5.1.2
- name: community.crypto
  version: 2.26.0
- name: community.general
  version: 10.5.0
- name: fedora.linux_system_roles
  version: 1.95.7
